# Generated by Django 4.2 on 2024-08-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                ("food_name", models.CharField(max_length=50)),
                ("spicy_preference", models.PositiveIntegerField()),
                ("intensity_preference", models.PositiveIntegerField()),
                ("oily_preference", models.PositiveIntegerField()),
                ("flour_rice_preference", models.PositiveIntegerField()),
                ("cost_preference", models.PositiveIntegerField()),
                ("spicy_weight", models.PositiveIntegerField()),
                ("cost_weight", models.PositiveIntegerField()),
                ("image_url", models.ImageField(upload_to="")),
                ("is_launch", models.BooleanField()),
                ("is_dinner", models.BooleanField()),
                ("is_snack", models.BooleanField()),
                ("is_date", models.BooleanField()),
                ("is_party", models.BooleanField()),
                ("is_diet", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
