# Generated by Django 4.2 on 2024-08-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="is_launch",
            new_name="is_lunch",
        ),
        migrations.RemoveField(
            model_name="food",
            name="food_filter",
        ),
    ]
