# Generated by Django 4.2 on 2024-08-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_timecategory"),
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FoodTag",
        ),
        migrations.AddField(
            model_name="food",
            name="food_filter",
            field=models.ManyToManyField(
                blank=True, null=True, to="categories.foodfilter"
            ),
        ),
    ]
