# Generated by Django 4.2 on 2024-10-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_number",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
