# Generated by Django 4.2 on 2024-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_fti_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
