# Generated by Django 4.2 on 2024-08-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="taste_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="fti_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
