# Generated by Django 4.2 on 2024-08-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="profile_image",
            new_name="profile_image_url",
        ),
    ]
