# Generated by Django 4.2 on 2024-08-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_taste_type_alter_customuser_fti_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="fti_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="taste_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
