# Generated by Django 4.2 on 2024-08-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
        ("comments", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewcomment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_comments",
                to="reviews.review",
            ),
        ),
    ]
