# Generated by Django 4.2 on 2024-08-23 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingmember",
            name="is_host",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meetingmember",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_id",
                to="meetings.meeting",
            ),
        ),
    ]
