# Generated by Django 4.2 on 2024-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0003_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reviewlike",
            constraint=models.UniqueConstraint(
                fields=("review", "user"), name="unique_review_user_like"
            ),
        ),
    ]
