# Generated by Django 4.2 on 2024-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0004_reviewlike_unique_review_user_like"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meetinglike",
            constraint=models.UniqueConstraint(
                fields=("meeting", "user"), name="unique_meeting_user_like"
            ),
        ),
    ]
