# Generated by Django 4.2 on 2024-10-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_ftitype_fti_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftitype",
            name="relation",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
