# Generated by Django 4.2 on 2024-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_ftitype_relation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ftitype",
            old_name="relation",
            new_name="bad_relation",
        ),
        migrations.AddField(
            model_name="ftitype",
            name="good_relation",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
