# Generated by Django 4.2 on 2024-08-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="is_host",
            field=models.BooleanField(default=True),
        ),
    ]
