# Generated by Django 4.2 on 2024-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_is_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="hits",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
