# Generated by Django 4.2 on 2024-08-20 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FtiTestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fti_question", models.TextField()),
                ("fti_question_image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="FtiType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fti_type", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TasteTestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taste_question", models.TextField()),
                ("taste_question_category", models.CharField(max_length=50)),
                (
                    "taste_question_image",
                    models.ImageField(default="abc.jpg", upload_to=""),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "fti_type",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_info.ftitype",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TasteTestAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taste_answer", models.CharField(max_length=100)),
                (
                    "taste_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_info.tastetestquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FtiTestAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fti_answer", models.TextField()),
                ("fti_style", models.CharField(max_length=10)),
                (
                    "fti_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_info.ftitestquestion",
                    ),
                ),
            ],
        ),
    ]
