# Generated by Django 4.2 on 2024-09-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftitestresult",
            name="fti_image_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
