# Generated by Django 4.2 on 2024-09-04 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_info", "0002_ftitestresult_fti_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ftitestresult",
            name="fti_image_url",
        ),
    ]
